<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="drone" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="mass" value="0.3" /> 
  <xacro:property name="size" value="0.5" />
  
  <xacro:property name="camera_size" value="0.2" />

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find drone_swarm)/urdf/drone.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find drone_swarm)/urdf/materials.xacro" />

  <link name="body">
    <visual>
      <origin xyz="0 0 ${size/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${size} ${size} ${size}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${size} ${size} ${size}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (size*size + size*size)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (size*size + size*size)}" iyz="0.0"
	  izz="${mass / 12.0 * (size*size + size*size)}" />
    </inertial>
  </link >


  <!-- Camera -->
  <link name="camera">
    <visual>
      <origin xyz="${camera_size/2} 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${camera_size} ${camera_size} ${camera_size}"/>
      </geometry>
      <material name="blue"/>
    </visual>
 
    <collision>
      <origin xyz="${camera_size/2} 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${camera_size} ${camera_size} ${camera_size}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link >

  <link name="camera_link_optical">
  </link>
  
  <joint name="camera_optical_joint" type="fixed">
    <!-- these values have to be these values otherwise the gazebo camera image
        won't be aligned properly with the frame it is supposedly originating from -->
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    <parent link="camera"/>
    <child link="camera_link_optical"/>
  </joint>

  <joint name="camera_joint" type="fixed">
    <parent link="body"/>
    <child link="camera"/>
    <origin xyz="${size/2} 0 ${size/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Hokuyo Laser -->
  <joint name="hokuyo_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0 0 -0.05" rpy="0 0 0"/>
    <parent link="body"/>
    <child link="hokuyo_link"/>
  </joint>

  <link name="hokuyo_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
      <material name="red"/>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>
  
</robot>
